import os

API_KEY_PAPER = os.getenv('ALPACA_API_KEY_PAPER')
SECRET_KEY_PAPER = os.getenv('ALPACA_SECRET_API_KEY_PAPER')
# API_KEY = os.getenv('ALPACA_API_KEY')
# SECRET_KEY = os.getenv('ALPACA_SECRET_API_KEY')

# print(API_KEY_PAPER, SECRET_KEY_PAPER)